### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by scpv** [verilylifesciences/genomewarp#14]
Hello,
I've followed the steps to build the .jar file, but I ran into this issue (after running mvn package):

> [ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project verilylifesciences-genomewarp: Missing:
> [ERROR] ----------
> [ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.0.0-beta-2
> [ERROR] 
> [ERROR]   Try downloading the file manually from the project website.
> [ERROR] 
> [ERROR]   Then, install it using the command: 
> [ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.0.0-beta-2 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
> [ERROR] 
> [ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
> [ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.0.0-beta-2 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
> [ERROR] 
> [ERROR]   Path to dependency: 
> [ERROR]   	1) com.verily.genomewarp:verilylifesciences-genomewarp:jar:1.2.1
> [ERROR]   	2) com.google.protobuf:protoc:exe:osx-aarch_64:3.0.0-beta-2
> [ERROR] 
> [ERROR] ----------
> [ERROR] 1 required artifact is missing.
> [ERROR] 
> [ERROR] for artifact: 
> [ERROR]   com.verily.genomewarp:verilylifesciences-genomewarp:jar:1.2.1
> [ERROR] 
> [ERROR] from the specified remote repositories:
> [ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

I also tried building manually, again using Gradle, and of course also following the steps in the error message to fix the issue. However, this hasn't worked. Would it be possible to provide the already built .jar file itself? Or am I missing something obvious here?

Thanks!

**Comment by pgrosu** [comment]
@scpv Is you Mac CPU based on M1/2 or x86?  

1) If x86 try the following:

`mvn clean package -DskipTests -Dos.detected.classifier=osx-x86_64`

2) If M1/2 try the following:

`mvn clean package -DskipTests -Dos.detected.classifier=osx-aarch_64`

**Comment by pgrosu** [comment]
@scpv So I don't think the above will work, but I have a possible solution for you.  I took a look through the repo here:

  [`https://repo1.maven.org/maven2/com/google/protobuf/protoc/`](https://repo1.maven.org/maven2/com/google/protobuf/protoc/)

And there is not `protoc` for `osx` with an `aarch` CPU for version `3.0.0-beta-2`, but there is for `3.23.1`.

So to fix it just open the `pom.xml` file, and update it as follows:

Change this line from (3.0.0-beta-2):
```
<protocArtifact>com.google.protobuf:protoc:3.0.0-beta-2:exe:${os.detected.classifier}</protocArtifact>
```
To the following (3.23.1):

```
<protocArtifact>com.google.protobuf:protoc:3.23.1:exe:${os.detected.classifier}</protocArtifact>
```

Then run it with the following to build the jar file:

```
mvn clean package -DskipTests
```

Some of the tests would need to updated in order for all the tests to pass, but it will build you the `jar` file under the `target` folder.

Let me know if this worked for you.

Thanks,
Paul

**Comment by scpv** [comment]
I have an M1 chip. First, I downloaded the .exe from your link, and ran this command:
mvn install:install-file -DgroupId=io.grpc -DartifactId=protoc-gen-grpc-java -Dversion=0.15.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/genomewarp/protoc-3.23.1-osx-aarch_64.exe

Then:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: aarch_64
[INFO] os.detected.classifier: osx-aarch_64
[INFO] 
[INFO] --------< com.verily.genomewarp:verilylifesciences-genomewarp >---------
[INFO] Building Verily Life Sciences GenomeWarp 1.2.1
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- install:3.1.0:install-file (default-cli) @ verilylifesciences-genomewarp ---
[INFO] Installing /path/to/genomewarp/protoc-3.23.1-osx-aarch_64.exe to /Users/user/.m2/repository/io/grpc/protoc-gen-grpc-java/0.15.0/protoc-gen-grpc-java-0.15.0-osx-aarch_64.exe
[INFO] BUILD SUCCESS
[WARNING] 
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-shade-plugin:2.3
[WARNING]  * org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]

Running the "mvn clean package -DskipTests" command gives:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: aarch_64
[INFO] os.detected.classifier: osx-aarch_64
[INFO] 
[INFO] --------< com.verily.genomewarp:verilylifesciences-genomewarp >---------
[INFO] Building Verily Life Sciences GenomeWarp 1.2.1
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ verilylifesciences-genomewarp ---
[INFO] Deleting /path/to/genomewarp/target
[INFO] 
[INFO] --- protobuf:0.5.0:compile (default) @ verilylifesciences-genomewarp ---
[INFO] Compiling 1 proto file(s) to /path/to/genomewarp/target/generated-sources/protobuf/java
[INFO] 
[INFO] --- protobuf:0.5.0:compile-custom (default) @ verilylifesciences-genomewarp ---
[INFO] Compiling 1 proto file(s) to /path/to/genomewarp/target/generated-sources/protobuf/grpc-java
[ERROR] PROTOC FAILED: [/there was a very long error message here, which I summarize now: Error: Protocol Compiler (protoc) failed to parse output of the gRPC Java plugin.

Usage: Run protoc-gen-grpc-java-0.15.0-osx-aarch_64.exe with options and proto files. Options include specifying import directories, showing version, encoding and decoding message types, deterministic map field ordering, reading arbitrary protocol messages, defining FileDescriptorSets, and generating various language output files.

For FileDescriptorSet, you can write them, include all input file dependencies, retain original location and comments, and retain compilation options. Error formats can be set to gcc or msvs, with an option to make warnings fatal. Free field numbers can be printed, codegen trace can be enabled, and plugins can be specified.

Output can be generated for C++, C#, Java, Kotlin, Objective-C, PHP, Python, Ruby, Rust. Options and filenames can also be read from a file, with each line corresponding to a single argument.]

[ERROR] /Users/user/path/to/genomewarp/src/main/proto/homologous_range.proto [0:0]: [another long error, which I summarize: Error: Unparseable output encountered while attempting to run protoc-gen-grpc-java-0.15.0-osx-aarch_64.exe on the homologous_range.proto file in the genomewarp project.

Solution: Execute the protoc-gen-grpc-java-0.15.0-osx-aarch_64.exe with appropriate options and proto files. These options can define import paths, encoding or decoding message types, deterministic outputs, raw decoding, specification of FileDescriptorSets, among others. 

Protoc can generate output files for various languages including C++, C#, Java, Kotlin, Objective-C, PHP, Python, Ruby, Rust. Options can also be read from a file. 

In case of issues, refer to the help text provided by the -h or --help option. Handle with care, as some options might inflate the descriptor size or make warnings fatal, affecting the successful completion of the task.]

[INFO] BUILD FAILURE

[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-shade-plugin:2.3
[WARNING]  * org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile-custom (default) on project verilylifesciences-genomewarp: protoc did not exit cleanly. Review output for more information. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Running the command without manually installing the .exe gives a similar error as the original post. Doing a replacement like "<protocExecutable>/Users/user/path/to/genomewarp/protoc-23.2-osx-aarch_64/bin/protoc</protocExecutable>" in the pom.xml also didn't work. It looks like this issue exists with other software on the M1 chip.

**Comment by pgrosu** [comment]
Also let's change this line:

```
<io.grpc.version>0.15.0</io.grpc.version>
```
To the following:

```
<io.grpc.version>1.55.1</io.grpc.version>
```
The reason for this change, is based on searching through the [gRPC codebase](https://github.com/search?q=repo%3Agrpc%2Fgrpc%203.23.1&type=code) for a matching gRPC version to protobuf version 3.23.1.  In the [gRPC codebase](https://github.com/search?q=repo%3Agrpc%2Fgrpc%203.23.1&type=code) it is listed as `1.57.0.dev0`, but that version is not yet available in the [Maven io.grpc.protoc repository](https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/) and the closest available one is 1.55.1.

**Comment by cmclean** [comment]
Thank you @pgrosu for looking into the dependency issues! They are very old. I've sent a pull request to update them which will hopefully resolve this error.

**Comment by pgrosu** [comment]
Sure thing @cmclean -- happy to help out :)  Glad to hear all is working well, and thank you for the PR.

Thanks,
~p

**Comment by cmclean** [comment]
@scpv I'm going to close this issue -- if you still have problems feel free to re-open it with the associated logs after syncing to this new version of the pom.xml.
