### ISSUE TITLE
Failed to map REF block

### ISSUE THREAD

**Issue by robertschmieder** [verilylifesciences/genomewarp#2]
Trying to convert this hg19 VCF to hg38:
https://storage.cloud.google.com/genomics-public-data/platinum-genomes/vcf/NA12880_S1.genome.vcf

Using the chain file from the README and a query BED file that covers all passing reference positions, the processing stops with the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Different reference for query variant and reference in query_range {
  reference_name: "chr1"
  start: 1584759
  end: 1584798
}
target_range {
  reference_name: "chr1"
  start: 1653313
  end: 1653352
}
target_strand: POSITIVE_STRAND
region_type: MISMATCHED_BASES

        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
        at com.verily.genomewarp.TransformationUnit.getTargetAssemblyVariantsFromDualSNVs(TransformationUnit.java:244)
        at com.verily.genomewarp.TransformationUnit.getTargetAssemblyVariants(TransformationUnit.java:163)
        at com.verily.genomewarp.TransformVariantsInRange.getTargetVariantsForAllTransformationUnitsInRange(TransformVariantsInRange.java:332)
        at com.verily.genomewarp.TransformVariantsInRange.transform(TransformVariantsInRange.java:162)
        at com.verily.genomewarp.TransformVariantsInRange.transformQueryToTargetVariants(TransformVariantsInRange.java:85)
        at com.verily.genomewarp.GenomeWarpSerial.main(GenomeWarpSerial.java:833)
```

Query entry causing the issue:
`chr1    1584760 .       C       .       .       PASS    END=1584798;BLOCKAVG_min30p3a   GT:DP:GQX:MQ    0/0:38:99:49`

HG19 (query_range sequence)

```
>chr1:1584760-1584798
caccc*g*gctttatttttatttttttcagatagaatctcg
```

HG38 (target_range sequence)

```
>chr1:1653314-1653352
CACCC*A*GCTTTATTTTTATTTTTTTCAGATAGAATCTCG
```

This part of the code performs a comparison of the first position of the query REF block (`C`) with the 6th position in the target REF block (`G`):
`https://github.com/verilylifesciences/genomewarp/blob/15a9a2a22c609dbe7f8bc1fe7818c8a8323cf165/src/main/java/com/verily/genomewarp/TransformationUnit.java#L245`

Line 245: `referenceGenomeDifference().queryDna().equals(variant.getReferenceBases()),`

Values compared by `.equals()`:
`referenceGenomeDifference()` = `{queryPosition=1584764, queryDna=G, targetDna=A}`
`variant.getReferenceBases()` = `C`

The query reference base for REF blocks will always be a single base and should not be compared to the n-th base with the difference in the target sequence.

**Comment by cmclean** [comment]
Thank you for the detailed error and analysis! As you discovered, handling a gVCF file is a currently unsupported use case, though it certainly could (and maybe should) be added in a future release. Currently, the BED file is meant to represent the confidently-called reference-matching bases.

As a workaround using the existing tool, you can filter the VCF to contain only variant records, using e.g.

`awk '$0 ~ "^#" || ($5 != "." && $5 != "<*>")' $GENOME_VCF > $VARIANT_VCF`

and then transform all the VCF entries into their corresponding BED records based on the given start and end (noting that BED is a zero-based half-open coordinate system whereas VCF is 1-based full closed). An example script to generate that BED file would be

`awk -F'\t' '$7 == "PASS"'
  '{start=$2 - 1;
     end=start + length($4);
     if ($8 != ".") {
       n=split($8, tokens, ";");
       for (i=1; i <= n; i++) {
         if(index(tokens[i], "END=") == 1) {
           end=substr(tokens[i], 5)
         }
       }
    }
    print $1 "\t" start "\t" end}' $GENOME_VCF > $BEDFILE`

**Comment by cmclean** [comment]
This issue was addressed by @pietropino 's pull request.
